### ISSUE TITLE
Not possible to see the SQL source of a TTS configuration

### ISSUE THREAD

**Issue by romone22** [Jarvis-Platform/tailer-studio#292]
**Describe the bug**
It's not possible to see the source SQL of a TTS configuration whereas it's possible to see it in the run detail view.

**To Reproduce**
1. Go to a TTS configuration 
2. It's not possible to view the SQL (no SQL button)
3. Go to a TTS run detail view
4. In the configuration tab of the run, you can view the SQL (visibility of the SQL button)

**Screenshots**

![image.png](https://images.zenhubusercontent.com/5dd7c2b29529f10001e6116d/ec9bb94e-6a1c-4493-9595-c9e5fc2f0dc5)
![image.png](https://images.zenhubusercontent.com/5dd7c2b29529f10001e6116d/46296db4-de1b-4459-9437-c9c10944f5f0)

**Comment by Eronne** [comment]
This is due to `sql` field in json which is an object with two properties & a binary string like this :
![image](https://user-images.githubusercontent.com/10868310/107891601-02b53a00-6f20-11eb-9724-0e1de5aaf792.png)

In most actual cases, I think it shows "No SQL Data" but there is this field in this form. How am I suppose to handle this?

**Comment by romone22** [comment]
The SQL is binary encrypted but it's possible to reverse it. We did it in another conf view (TTT I guess). The code is available is already availale in studio somewhere :)

**Comment by Eronne** [comment]
When I decode the binary String, it returns me weird values.
